Module6-task1
Onixel26/2522965-cat-energy-2 pull request #11
Opened 2024-11-01 06:59 UTC by Onixel26

Адаптив сетка на оба файла index html, catalog html

2024-11-01 13:07 UTC, brewscriptor requested changes

2024-11-01 13:07 UTC, brewscriptor commented on source/styles/blocks/catalog-layout.scss
> +  @media (min-width: 560px) {
🟡 можем ли мы использовать переменные ширины вьюпорта?
$width-tablet, $width-desktop и тд?
и если нет, то почему?
как новый разработчик на проекте, я могу не понять почему именно на 560рх нам надо что-то менять

2024-11-01 13:07 UTC, brewscriptor commented on source/styles/blocks/catalog-layout.scss
> +    margin-bottom: 23.4px;
🔴 пиксели не нужно указывать с дробными долями. округли по правилам математики и будет ок.
это уложится в допустимые отклонения.

2024-11-01 13:07 UTC, brewscriptor commented on source/styles/blocks/contacts.scss
> +    box-sizing: border-box;
🔴 это должно быть где-то на самом верху, например в боди.
у нас в критериях указано, что изначально `box-sizing: border-box;` должен распространяться на весь проект

2024-11-01 13:07 UTC, brewscriptor commented on source/styles/blocks/preview.scss
> +    box-sizing: border-box;
🔴 тоже

2024-11-01 13:07 UTC, brewscriptor commented on source/styles/common/global.scss
> +*::before,
🟡 таким образом не нужно будет прописывать это в каждом месте
*,
*::before,
*::after {
    box-sizing: border-box;
}

2024-11-02 11:14 UTC, Onixel26 commented on source/styles/blocks/catalog-layout.scss
> +  @media (min-width: 560px) {
> 🟡 можем ли мы использовать переменные ширины вьюпорта? $width-tablet, $width-desktop и тд? и если нет, то почему? как новый разработчик на проекте, я могу не понять почему именно на 560рх нам надо что-то менять

в таком случае надо сделать подвязку комментарием? Или попытаться донести через введение доп. переменной?

К примеру это случай, когда адаптив разметки меняется из за освобождения доп свободного места для появления дополнительной 3 колонки грида (свойство auto fit). Подобное ж по идеи не определить в пару слов в переменную...

2024-11-02 11:38 UTC, brewscriptor commented on source/styles/blocks/catalog-layout.scss
> +  @media (min-width: 560px) {
> > 🟡 можем ли мы использовать переменные ширины вьюпорта? $width-tablet, $width-desktop и тд? и если нет, то почему? как новый разработчик на проекте, я могу не понять почему именно на 560рх нам надо что-то менять
> 
> 
> 
> в таком случае надо сделать подвязку комментарием? Или попытаться донести через введение доп. переменной?
> 
> 
> 
> К примеру это случай, когда адаптив разметки меняется из за освобождения доп свободного места для появления дополнительной 2 колонки грида (свойство auto fit). Подобное ж по идеи не определить в пару слов в переменную...

окей, в таком случае можно оставить коммент, чтобы было разъяснение базовое

2024-11-03 06:34 UTC, merged